### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mdentremont** [moq/labs#2]
I'm just wondering where I can find documentation for this framework?

Edit: I did eventually find it in the Moq4 repo - but this was after going to this repo, the github site, and some other pages. It might be nice to have links to the v4 wiki from here and the github site.

**Comment by kzu** [comment]
Literally the *first* google hit for "moq documentation" is the Wiki. Not planning on adding anything related to the currently shipping version to this repo which is about vNext. I'm planning on revamping the whole doc thing on top of docfx eventually.

Thanks for your understanding!

**Comment by mdentremont** [comment]
Thanks @kzu, I think what got me was the link on the Nuget page takes me to the github site that doesn't have documentation.

**Comment by kzu** [comment]
Sigh, really?! 

Fixed! https://github.com/moq/moq4/commit/39292ed2fedfac4a38f60affd840678cb6d163c1 

:)

**Comment by mdentremont** [comment]
Yay thanks!
