### ISSUE TITLE
Build: ensure that code generating tasks are idempotent

### ISSUE THREAD

**Issue by KirillOsenkov** [moq/labs#24]
Looks like the build tasks writing files such as `C:\moq\src\Stunts\Stunts\obj\Debug\ThisAssembly.ProjectProperties.g.cs` will write the file even if the existing text content is exactly the same. 

For proper incremental builds consider changing that logic so that it first reads the text from the file if it exists, compares, and only writes the text if it's different from what is already there.

There are issues against MSBuild to make these changes to the WriteLinesToFile and WriteCodeFragment tasks: https://github.com/Microsoft/msbuild/issues/3597

**Comment by kzu** [comment]
Switched to using the `AssemblyMetadata` approach for this instead.
