### ISSUE TITLE
Build: consider getting rid of inline tasks in the build

### ISSUE THREAD

**Issue by KirillOsenkov** [moq/labs#25]
They use very slow CodeDOM for code generation.

**Comment by kzu** [comment]
We could just switch to the built-in Roslyn one and it would be awesome automatically?

**Comment by KirillOsenkov** [comment]
I’ve later discovered that the Roslyn one has its problems (It was not caching properly, so doing expensive work every time). So maybe write a task .dll by hand or just leave it alone if you’re happy with perf. Or let’s fix the Roslyn one and use it then :)

**Comment by kzu** [comment]
Switched to source generators 💪
